# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='typez',
            field=models.TextField(default=True),
        ),
    ]
