# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_typez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='typez',
            field=models.CharField(max_length=10),
        ),
    ]
