# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171021_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite_fruit',
            field=models.CharField(default='Faculty', max_length=10),
        ),
    ]
