# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171021_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='color',
            field=models.CharField(choices=[('faculty', 'FACULTY'), ('office', 'OFFICE'), ('committee', 'COMMITTEE'), ('campus', 'CAMPUS')], default='Faculty', max_length=10),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
